sonar.projectKey=apchavez_devops-swarm-challenge
sonar.projectName=devops-swarm-challenge
sonar.organization=apchavez
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
